controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

exercise_list:
    path: /exercises
    controller: App\Controller\ExerciseController::index

user_list:
    path: /users
    controller: App\Controller\UserController::index
